"""Initial migration

Revision ID: 295f05c1aa54
Revises: 
Create Date: 2024-09-16 16:51:42.830716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295f05c1aa54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('card_used', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('card_used', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electric', sa.Float(), nullable=False),
    sa.Column('water', sa.Float(), nullable=False),
    sa.Column('internet', sa.Float(), nullable=False),
    sa.Column('household_item', sa.Float(), nullable=False),
    sa.Column('electric_start_date', sa.Date(), nullable=False),
    sa.Column('electric_end_date', sa.Date(), nullable=False),
    sa.Column('water_start_date', sa.Date(), nullable=False),
    sa.Column('water_end_date', sa.Date(), nullable=False),
    sa.Column('internet_start_date', sa.Date(), nullable=False),
    sa.Column('internet_end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utility')
    op.drop_table('gas')
    op.drop_table('expense')
    # ### end Alembic commands ###
