"""Add new Stock model

Revision ID: 417c2217d332
Revises: f399de23e3fa
Create Date: 2024-09-25 22:10:28.606902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417c2217d332'
down_revision = 'f399de23e3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('last_updated')
        batch_op.drop_column('current_price')

    # ### end Alembic commands ###
