"""added investment history db

Revision ID: 4e0da66d6be1
Revises: 8644ca963152
Create Date: 2024-09-30 01:15:51.529321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0da66d6be1'
down_revision = '8644ca963152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment__history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('eod_initial_investment', sa.Float(), nullable=True),
    sa.Column('eod_investment', sa.Float(), nullable=True),
    sa.Column('percent_diff', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment__history')
    # ### end Alembic commands ###
